In [2]:
import mysql.connector

conn = mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password="Keerthan@12"
)

print("Connected Successfully")

Connected Successfully

In [3]:
import mysql.connector

conn = mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password="Keerthan@12",
    database="CustomerDB"
)

cursor = conn.cursor()

print("Connected Successfully")

Connected Successfully

In [5]:
import pandas as pd

df = pd.read_csv("customers.csv")

print(df.head())

   CustomerID CustomerName       City            Email  Age    JoinDate  \
0         101        Rahul  Hyderabad  rahul@gmail.com   25  2023-01-10
1         102        Priya    Chennai  priya@gmail.com   28  2023-02-15
2         103        Arjun  Bangalore  arjun@gmail.com   30  2023-03-20
3         104        Sneha  Hyderabad  sneha@gmail.com   27  2023-04-25
4         105        Kiran    Chennai              NaN   29  2023-05-10

   TotalPurchase
0           5000
1           7000
2           9000
3           6000
4           8000

In [6]:
df["Email"] = df["Email"].fillna("Not Available")

df.drop_duplicates(inplace=True)

df["JoinDate"] = pd.to_datetime(df["JoinDate"])

print(df)

   CustomerID CustomerName       City            Email  Age   JoinDate  \
0         101        Rahul  Hyderabad  rahul@gmail.com   25 2023-01-10
1         102        Priya    Chennai  priya@gmail.com   28 2023-02-15
2         103        Arjun  Bangalore  arjun@gmail.com   30 2023-03-20
3         104        Sneha  Hyderabad  sneha@gmail.com   27 2023-04-25
4         105        Kiran    Chennai    Not Available   29 2023-05-10

   TotalPurchase
0           5000
1           7000
2           9000
3           6000
4           8000

In [7]:
print(df.shape)
print(df.head())

(5, 7)
   CustomerID CustomerName       City            Email  Age   JoinDate  \
0         101        Rahul  Hyderabad  rahul@gmail.com   25 2023-01-10
1         102        Priya    Chennai  priya@gmail.com   28 2023-02-15
2         103        Arjun  Bangalore  arjun@gmail.com   30 2023-03-20
3         104        Sneha  Hyderabad  sneha@gmail.com   27 2023-04-25
4         105        Kiran    Chennai    Not Available   29 2023-05-10

   TotalPurchase
0           5000
1           7000
2           9000
3           6000
4           8000

In [8]:
cursor = conn.cursor()

for row in df.itertuples(index=False):
    cursor.execute("""
        INSERT INTO Customers
        VALUES (%s,%s,%s,%s,%s,%s,%s)
    """, tuple(row))

conn.commit()

print("Data Inserted Successfully")

Data Inserted Successfully

In [9]:
query="""SELECT * FROM Customers"""
pd.read_sql(query,engine)

NameError: name 'engine' is not defined

In [10]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\keerthan\anaconda3\lib\site-packages (2.0.25)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\keerthan\anaconda3\lib\site-packages (from sqlalchemy) (4.13.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\keerthan\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [11]:
import pandas as pd

data = {
    "CustomerID": [101,102,103,104,105,105],
    "CustomerName": ["Rahul","Priya","Arjun","Sneha","Kiran","Kiran"],
    "City": ["Hyderabad","Chennai","Bangalore","Hyderabad","Chennai","Chennai"],
    "Email": [
        "rahul@gmail.com",
        "priya@gmail.com",
        "arjun@gmail.com",
        "sneha@gmail.com",
        None,
        None
    ],
    "Age": [25,28,30,27,29,29],
    "JoinDate": [
        "2023-01-10",
        "2023-02-15",
        "2023-03-20",
        "2023-04-25",
        "2023-05-10",
        "2023-05-10"
    ],
    "TotalPurchase": [5000,7000,9000,6000,8000,8000]
}

df_customers = pd.DataFrame(data)

df_customers.to_csv("customers.csv", index=False)

df_customers

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,101,Rahul,Hyderabad,rahul@gmail.com,25,2023-01-10,5000
1,102,Priya,Chennai,priya@gmail.com,28,2023-02-15,7000
2,103,Arjun,Bangalore,arjun@gmail.com,30,2023-03-20,9000
3,104,Sneha,Hyderabad,sneha@gmail.com,27,2023-04-25,6000
4,105,Kiran,Chennai,None,29,2023-05-10,8000
5,105,Kiran,Chennai,None,29,2023-05-10,8000

In [12]:
df = pd.read_csv("customers.csv")

df

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,101,Rahul,Hyderabad,rahul@gmail.com,25,2023-01-10,5000
1,102,Priya,Chennai,priya@gmail.com,28,2023-02-15,7000
2,103,Arjun,Bangalore,arjun@gmail.com,30,2023-03-20,9000
3,104,Sneha,Hyderabad,sneha@gmail.com,27,2023-04-25,6000
4,105,Kiran,Chennai,NaN,29,2023-05-10,8000
5,105,Kiran,Chennai,NaN,29,2023-05-10,8000

In [13]:
# Fill null values

df["Email"] = df["Email"].fillna("Not Available")

# Remove duplicates

df = df.drop_duplicates()

# Convert JoinDate

df["JoinDate"] = pd.to_datetime(df["JoinDate"])

df

C:\Users\Keerthan\AppData\Local\Temp\ipykernel_16800\1076578474.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["JoinDate"] = pd.to_datetime(df["JoinDate"])

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,101,Rahul,Hyderabad,rahul@gmail.com,25,2023-01-10,5000
1,102,Priya,Chennai,priya@gmail.com,28,2023-02-15,7000
2,103,Arjun,Bangalore,arjun@gmail.com,30,2023-03-20,9000
3,104,Sneha,Hyderabad,sneha@gmail.com,27,2023-04-25,6000
4,105,Kiran,Chennai,Not Available,29,2023-05-10,8000

In [14]:
total_purchase = df["TotalPurchase"].sum()

print("Total Purchase:", total_purchase)

Total Purchase: 35000

In [15]:
city_revenue = (
    df.groupby("City")["TotalPurchase"]
      .sum()
      .reset_index()
)

city_revenue

        City  TotalPurchase
0  Bangalore           9000
1    Chennai          15000
2  Hyderabad          11000

In [16]:
city_count = (
    df.groupby("City")["CustomerID"]
      .count()
      .reset_index()
)

city_count

        City  CustomerID
0  Bangalore           1
1    Chennai           2
2  Hyderabad           2

In [17]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:YOUR_PASSWORD@localhost:3306/CustomerDB"
)

engine

Engine(mysql+mysqlconnector://root:***@localhost:3306/CustomerDB)

In [18]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:Keerthan@12@localhost:3306/CustomerDB"
)

engine

Engine(mysql+mysqlconnector://root:***@12@localhost:3306/CustomerDB)

In [20]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("Keerthan@12")

engine = create_engine(
    f"mysql+mysqlconnector://root:{password}@localhost:3306/CustomerDB"
)

print(engine)

Engine(mysql+mysqlconnector://root:***@localhost:3306/CustomerDB)

In [21]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT DATABASE();"))
    print(result.fetchone())

('customerdb',)

In [22]:
df.to_sql(
    name="customer_fact",
    con=engine,
    if_exists="replace",
    index=False
)

print("Customer Fact Loaded")

Customer Fact Loaded

In [23]:
city_revenue = (
    df.groupby("City")["TotalPurchase"]
      .sum()
      .reset_index()
)

city_revenue.to_sql(
    name="customer_city_summary",
    con=engine,
    if_exists="replace",
    index=False
)

print("Summary Loaded")

Summary Loaded

In [24]:
import pandas as pd

pd.read_sql(
    "SELECT * FROM customer_fact",
    con=engine
)

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,101,Rahul,Hyderabad,rahul@gmail.com,25,2023-01-10,5000
1,102,Priya,Chennai,priya@gmail.com,28,2023-02-15,7000
2,103,Arjun,Bangalore,arjun@gmail.com,30,2023-03-20,9000
3,104,Sneha,Hyderabad,sneha@gmail.com,27,2023-04-25,6000
4,105,Kiran,Chennai,Not Available,29,2023-05-10,8000

In [25]:
pd.read_sql(
    "SELECT * FROM customer_city_summary",
    con=engine
)

        City  TotalPurchase
0  Bangalore           9000
1    Chennai          15000
2  Hyderabad          11000

In [26]:
pd.read_sql(
"""
SELECT COUNT(*) AS TotalCustomers
FROM customer_fact
""",
con=engine
)

   TotalCustomers
0               5

In [27]:
pd.read_sql(
"""
SELECT CustomerName,
       TotalPurchase
FROM customer_fact
ORDER BY TotalPurchase DESC
LIMIT 5
""",
con=engine
)

  CustomerName  TotalPurchase
0        Arjun           9000
1        Kiran           8000
2        Priya           7000
3        Sneha           6000
4        Rahul           5000

In [28]:
pd.read_sql(
"""
SELECT City,
       SUM(TotalPurchase) AS Revenue
FROM customer_fact
GROUP BY City
""",
con=engine
)

        City  Revenue
0  Hyderabad  11000.0
1    Chennai  15000.0
2  Bangalore   9000.0

In [29]:
pd.read_sql(
"""
SELECT City,
       COUNT(*) AS CustomerCount
FROM customer_fact
GROUP BY City
""",
con=engine
)

        City  CustomerCount
0  Hyderabad              2
1    Chennai              2
2  Bangalore              1

In [30]:
pd.read_sql(
"""
SELECT CustomerName,
       TotalPurchase,
       RANK() OVER(
       ORDER BY TotalPurchase DESC
       ) AS RankNo
FROM customer_fact
""",
con=engine
)

  CustomerName  TotalPurchase  RankNo
0        Arjun           9000       1
1        Kiran           8000       2
2        Priya           7000       3
3        Sneha           6000       4
4        Rahul           5000       5

In [32]:
pd.read_sql(
"""
SELECT CustomerName,
       TotalPurchase,
       RANK() OVER(
       ORDER BY TotalPurchase DESC
       ) AS RankNo
FROM customer_fact
""",
con=engine
)

  CustomerName  TotalPurchase  RankNo
0        Arjun           9000       1
1        Kiran           8000       2
2        Priya           7000       3
3        Sneha           6000       4
4        Rahul           5000       5

In [33]:
query="""
SELECT CustomerName,
       TotalPurchase,
       RANK() OVER(
       ORDER BY TotalPurchase DESC
       ) AS RankNo
FROM customer_fact
"""
pd.read_sql(
    query,engine
)

  CustomerName  TotalPurchase  RankNo
0        Arjun           9000       1
1        Kiran           8000       2
2        Priya           7000       3
3        Sneha           6000       4
4        Rahul           5000       5

In [34]:
pd.read_sql(
"""
SELECT *
FROM customer_fact
WHERE TotalPurchase >
(
    SELECT AVG(TotalPurchase)
    FROM customer_fact
)
""",
con=engine
)

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,103,Arjun,Bangalore,arjun@gmail.com,30,2023-03-20,9000
1,105,Kiran,Chennai,Not Available,29,2023-05-10,8000

In [35]:
pd.read_sql(
"""
SELECT YEAR(JoinDate) AS Year,
       MONTH(JoinDate) AS Month,
       COUNT(*) AS CustomersJoined
FROM customer_fact
GROUP BY YEAR(JoinDate),
         MONTH(JoinDate)
ORDER BY Year, Month
""",
con=engine
)

   Year  Month  CustomersJoined
0  2023      1                1
1  2023      2                1
2  2023      3                1
3  2023      4                1
4  2023      5                1